### ISSUE TITLE
query_string_auth

### ISSUE THREAD

**Issue by spydarkone** [pixelpeter/laravel5-woocommerce-api-client#10]
How can we set this option to true, when calling an API method? I keep getting the error "Sorry, you cannot view this resource. [woocommerce_rest_cannot_view]". But when I try exactly the same call using the official API Client, it works fine:

$woocommerce = new \Automattic\WooCommerce\Client(
    'https://example.com',
    'consumer_key',
    'consumer_secret',
    [
        'wp_api' => true,
        'version' => 'wc/v1',
        'query_string_auth' => true // Force Basic Authentication as query string true and using under HTTPS
    ]
);

**Comment by pixelpeter** [comment]
This is possible with the new release 2.1.0
https://github.com/pixelpeter/laravel5-woocommerce-api-client/releases/tag/v2.1.0
