### ISSUE TITLE
Error: Sorry, you cannot list resources. [woocommerce_rest_cannot_view]

### ISSUE THREAD

**Issue by raunak-gupta** [pixelpeter/laravel5-woocommerce-api-client#12]
I'm using "pixelpeter/laravel5-woocommerce-api-client": "2.0" to connect with my WooCommerce store, but i'm getting an error which says 

> HttpClientException in HttpClient.php line 320:
> Error: Sorry, you cannot list resources. [woocommerce_rest_cannot_view]

My code is

```
use Woocommerce;

public function getIndex() {
    $data = [
        'id' => '2626'
    ];

    $result = Woocommerce::get('orders', $data);
    print_r($result);
}
```

My site has SSL. (store_url = https://www.example.com/)

Laravel Version: 5.2.*
WordPress Version: 4.6.1
WooCommerce Version: 2.6.8

![2016-11-25_1042](https://cloud.githubusercontent.com/assets/22704179/20615076/f2c147fe-b2fb-11e6-98db-ad2d4acec983.png)

**Comment by simofacc** [comment]
@raunak-gupta Hi, because you are using a URL with https you need to enable
`WOOCOMMERCE_WP_QUERY_STRING_AUTH=true`
in the laravel .env config file, then you won't get this error given that the key and secret are correctly set.

**Comment by pixelpeter** [comment]
@simofacc Thanks for helping me out with support
