### ISSUE TITLE
HttpClientException: Syntax error

### ISSUE THREAD

**Issue by jfvoliveira** [pixelpeter/laravel5-woocommerce-api-client#17]
Hi there. I've got an error while trying to use this api client.

```
// routes/web.php
Route::get('/woo', 'WooController@woo')->name('woo');
```

```
// WooController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;

use Woocommerce;

class WooController extends Controller
{
	public function woo()
	{
		return Woocommerce::get('orders');
	}
}
```

When I go to /woo, I get an error:

https://i.imgur.com/3l1W6SG.png

Am I doing anything wrong?

Btw, I am using WooCommerce 2.6.14, the API is enabled and the key configured. Permalinks are not the defaults. In the .env, WOOCOMMERCE_VERSION=v2 with your 2.3.0 version.

**Comment by pixelpeter** [comment]
It needs to be `WOOCOMMERCE_VERSION=v1` because Woocommerce 2.7 was dropped and 3.0 is still only a release candidate.
So I assume you'll use Woocommerce 2.6 and this is the coerect version for this

**Comment by arie-piscator** [comment]
This error can also be triggered when the `WOOCOMMERCE_STORE_URL` setting is wrong.

**Comment by pixelpeter** [comment]
@arie-piscator Thanks for pointing this out

**Comment by teejei** [comment]
I still getting this error using laravel 5.5 and WC 3.1.2.

**Comment by riksnelders** [comment]
Getting this error . WC Version = 3.3.5
