### ISSUE TITLE
how to get order list?

### ISSUE THREAD

**Issue by heinhtut95** [pixelpeter/laravel5-woocommerce-api-client#18]
I finished all the 5 steps already and 
I added use Woocommerce;
and     public function index()
    {
        return Woocommerce::get('orders'); in PostController.

But its showing the error ike this ,please guide me. Thanks.

>  HttpClientException in HttpClient.php line 340:
> Syntax error

**Comment by Johtec2000** [comment]
Make sure API URI is reachable (ModRewrite + htaccess).

**Comment by JoshuaCallis** [comment]
I've followed all of your steps and have added **use Woocommerce;** 
in the  **TestController**, however I received the Class 'Woocommerce' not found error. Do you know why this is :)?
<?php

namespace App\Http\Controllers;

use View;
use Woocommerce;
use Illuminate\Http\Request;
use App\Http\Requests;

class TestController extends Controller
{

    
    public function test()
    {

        return Woocommerce::get('orders');
    }
}

**Comment by pixelpeter** [comment]
You can also check if your api is working correctly (without authentication) by calling 
```
[your.domain]/wp-json/wc/v2
```
