### ISSUE TITLE
Woocommerce api V2?

### ISSUE THREAD

**Issue by imalitavakoli** [pixelpeter/laravel5-woocommerce-api-client#19]
Does your wrapper also support the [V2 api](http://woocommerce.github.io/woocommerce-rest-api-docs/#introduction), I mean WC V3?
Thanks for your awesome Laravel wrapper. It's cool 👍

**Comment by pixelpeter** [comment]
You'll just need to update `WOOCOMMERCE_VERSION` to `v2` in your configuration
```
// app/config/woocommerce
 'api_version' => env('WOOCOMMERCE_VERSION', 'v2'),
```
and it will work.

With the next version which will also support Laravel 5.5 `v2`  will be the default
