### ISSUE TITLE
Is there a problem with products route

### ISSUE THREAD

**Issue by limeframe** [pixelpeter/laravel5-woocommerce-api-client#2]
Hi!
Is there a problem with products route?
I have tested : orders, customers, coupons , products/categories and all of them have a responses.
But when i try return Woocommerce::get('products'); terminate the  connection and i am getting a
 No data received

ERR_EMPTY_RESPONSE

Thanks

**Comment by pixelpeter** [comment]
This is a duplicate of https://github.com/woothemes/wc-api-php/issues/4
