### ISSUE TITLE
Integration with other WordPress Laravel API's / Transactions

### ISSUE THREAD

**Issue by nickbluestone98** [pixelpeter/laravel5-woocommerce-api-client#22]
Hello,

Just a few quick questions, I would appreciate if you could answer 👍 

1. Is your API dependant on https://github.com/woocommerce/wc-api-php ?
2. Do you know if your API would work alongside https://github.com/corcel/corcel ? 
3. How to the physical transactions work? Does your API handle these?

Kind Regards,

Nick.

**Comment by pixelpeter** [comment]
Hi NIck

Sorry for being late ...

Here are the answers
1. YES
This library depends on https://github.com/woocommerce/wc-api-php and is just a light wrapper around it for easy Laravel integration.
2. YES
Why shouldn't it ? Corcel is using a database connection to your Wordpress installation while the wc-api makes http calls to the build-in REST API of Wordpress.
I use corcel also in my projects to get some meta data not returned from the REST API
3. ???
I don't know exactly what you mean. This is just a wrapper which doesn't add any functionality. If you eant to know how transactions are handled please have a direct look at https://github.com/woocommerce/wc-api-php
