### ISSUE TITLE
Client response error

### ISSUE THREAD

**Issue by riksnelders** [pixelpeter/laravel5-woocommerce-api-client#24]
Importing a few products with the package.

Expected behaviour:
Continue with next product.

freezes on product with multiple images, then throws Syntax error in HttpClient.php on line 346.

**Comment by pixelpeter** [comment]
This package is only a wrapper around the `woocommerce/wc-api-php`.
I don't add any additional functionality.
So this looks like an issue with the underlying library.

Everything else is working?!

**Comment by riksnelders** [comment]
It seems to be working fine if i don't more than 1 image yes. Also the errors thrown are dutch. That part of the wrapper?  or the wc-api ?

**Comment by pixelpeter** [comment]
That's coming from the wc-api or the settings of your woocommerce shop.
