### ISSUE TITLE
set dynamic credentials for woocommerce

### ISSUE THREAD

**Issue by sattip** [pixelpeter/laravel5-woocommerce-api-client#25]
I would like to know if we have the ability to set the credentials using code dynamic for example to load them from the database. I noticed a config file only

**Comment by pixelpeter** [comment]
I'm afraid that this is not possible when using the facade.
You could initialize the underlying `WoocoomerceClient` by yourself, but then there's no reason to use this wrapper. instead of the wc-api directly.
