### ISSUE TITLE
regular_price invalid param

### ISSUE THREAD

**Issue by riksnelders** [pixelpeter/laravel5-woocommerce-api-client#26]
Error thrown when using regular_price.
Also price is not updating, while stock_quantity is updating.

Any ideas? Maybe the dependencies for this package?

```
 $data = [
                    'price' => $product->artikelsoort == "verhuur" ? $product->verhuurprijs : $product->verkoopprijs,
                    'regular_price' => $product->artikelsoort == "verhuur" ? $product->verhuurprijs : $product->verkoopprijs,
                    'stock_quantity' => $stock->voorraad,
                    'in_stock'=>  $stock->voorraad > 0 ? true : false
                ];
```

**Comment by pixelpeter** [comment]
`automattic/woocommerce` updated to 2.0.0 on 2018.01.18 but this package still uses 1.3.* !
So I assume it's not related to the dependencies of this package.

I'll will check this further

**Comment by riksnelders** [comment]
solved. Wordpress requires a price to be string.
fml wordpress..
