### ISSUE TITLE
Register Products

### ISSUE THREAD

**Issue by fabianomoier** [pixelpeter/laravel5-woocommerce-api-client#27]
Good Morning!!
When registering products I am with test array of the form below

Array
(
    [title] => Geladeira
    [type] => simple
    [regular_price] => 5900.00
    [description] => Side by Side com gelo na porta
    [categories] => 1
    [stock_quantity] => 2
    [in_stock] => true
)

my question is to save in Woo the products passed by array I am using as below
return Woocommerce::put($params_produto);

"Type error: Too few arguments to function Pixelpeter\Woocommerce\WoocommerceClient::put(), 1 passed in  vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php on line 221 and exactly 2 expected ◀"

Sorry, I may be doing it wrong !! Thank you very much!!

**Comment by pixelpeter** [comment]
You forgot to define the endpoint.
It needs to be:
```
return Woocommerce::put('products', $params_produto);
```

**Comment by fabianomoier** [comment]
Yes!!
Thank you so much !!

**Comment by fabianomoier** [comment]
I tried to register the product I received this error!
"Error: No route found that matches the URL and request method [rest_no_route]"

**Comment by fabianomoier** [comment]
My role was this way.
public function everestprodutos(){
        $produtos = Listaprodutos::all();
         foreach ($produtos as $produto) {
                  $params_produto = [   
                        //'title' => $produto->cd_item,
                        'name' => $produto->descricao,
                        'type' => "simple",    
                        'status' => "publish",
                        'featured' => false,
                        'catalog_visibility' => "visible", 
                        'sku' => $produto->cd_item,        
                        'description' => " ",
                        'regular_price' => $produto->vl_preco,
                        'stock_quantity' => $produto->qt_saldo,
                        'categories' => $produto->nm_gde_grupo,
                        'in_stock' => "true",
                   ];                     
                }
              
                   return Woocommerce::put('products', $params_produto);
                      
    }
