### ISSUE TITLE
[rest_no_route]

### ISSUE THREAD

**Issue by fabianomoier** [pixelpeter/laravel5-woocommerce-api-client#30]
I tried to register the product I received this error!
"Error: No route found that matches the URL and request method [rest_no_route]"

My role was this way.
https://pastebin.com/2K6MNfuQ

**Comment by pixelpeter** [comment]
It needs to be `Woocommerce::post('products', $params);` (not `put`)

 Have a look at the documentation:
https://woocommerce.github.io/woocommerce-rest-api-docs/#create-a-product

**Comment by fabianomoier** [comment]
What would be the correct way to send the value of the category that is in $ tr?
Erro >> "Error: Parâmetro(s) inválido(s): categories [rest_invalid_param]"

` $params_produto = [   
                        //'title' => $produto->cd_item,
                        'name' => $produto->descricao,
						//'categories' => array ( 'id' => $tr),
                        'categories' => [
                            [
                                'id' => $tr 
                            ],                              
                        ],
                        'in_stock' => "true",
                        'manage_stock' => "true",
                   ]; `
