### ISSUE TITLE
he i have small question   

### ISSUE THREAD

**Issue by almokhtarbr** [pixelpeter/laravel5-woocommerce-api-client#35]
i have web app built with laravel and a website with wordpress (woocomerce) so i want to get all orders from this site so my question if i have more than 1 website with woocomerce what i must do ?
Salutaions

**Comment by pixelpeter** [comment]
I don't get exactly what you mean.
You have **one** Laravel application that will get orders from **multiple** Woocommerce stores?

**Comment by almokhtarbr** [comment]
@pixelpeter exactly that what i mean .

**Comment by HeathMorrisCode** [comment]
I have the same question! I have 3 separate WooCommerce shops that I would like to pull order data from. I'm wondering if there is an easy way to retrofit this library to do that, or if I should just use the official PHP wrapper.
Keep up the great work, this library has been hugely useful for me, thanks again!
