### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Mehul-tk** [pixelpeter/laravel5-woocommerce-api-client#37]
Hello, 

Great project thank you for your tremendous work 
 
I am using laravel 5.6 and php7.1 i try to use this in my project but it's give errror
here is the error:
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for pixelpeter/laravel5-woocommerce-api-client 3.0 -> satisfiable by pixelpeter/laravel5-woocommerce-api-client[v3.0.0].
    - pixelpeter/laravel5-woocommerce-api-client v3.0.0 requires automattic/woocommerce 1.3.* -> satisfiable by automattic/woocommerce[1.3.0] but these conflict with your requirements or minimum-stability.

how can i solved it something i missed out or version issues

**Comment by pixelpeter** [comment]
Please show me you composer.json so I can help you

**Comment by pixelpeter** [comment]
Closing because no additional information provided
