### ISSUE TITLE
list all product problem

### ISSUE THREAD

**Issue by konservasi** [pixelpeter/laravel5-woocommerce-api-client#38]
Hai pixelpeter,

I have installed this module to my laravel. I need to list all product. I have read issue #13 you gave us a solution how to make pagination. My question is how can we take the data at $param variable. I have no idea how to take the $param parameter.

Need assistant

**Comment by pixelpeter** [comment]
Please describe your problem more detailed so I can help you or have a look at the guide for pagination https://github.com/pixelpeter/laravel5-woocommerce-api-client#pagination

**Comment by konservasi** [comment]
Oke. I will share all the code here so that you can review. I dont know excactly what's wrong with my code. Please review and fix.

This is my ProductController.php

<?php

namespace App\Http\Controllers;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Woocommerce;

public function show ($id)
    {
      $params = [
        'per_page' => 10,
        'page' => $id
        ];

        Woocommerce::get('products');
        $current = Woocommerce::currentPage();
        $previous = Woocommerce::previousPage();
        $next = Woocommerce::nextPage();
        $firstpage = Woocommerce::firstPage();
        $lastpage = Woocommerce::lastPage();

      return view ('product', ['params' => $params, 'firstpage' => $firstpage, 'lastpage' => $lastpage, 'current' => $current, 'previous' => $previous, 'next' => $next]);

    }

this is my product.blade.php

@extends('layouts.header')

@section('content')
<span class="heading">Main</span>
<ul class="list-unstyled">
          <li><a href="tables.html"> <i class="icon-grid"></i>Tables </a></li>
          <li><a href="#exampledropdownDropdown" aria-expanded="false" data-toggle="collapse"> <i class="icon-interface-windows"></i>Example dropdown </a>
            <ul id="exampledropdownDropdown" class="collapse list-unstyled ">
              <li><a href="#">Page</a></li>
              <li><a href="#">Page</a></li>
              <li><a href="#">Page</a></li>
            </ul>
          </li>
</ul>
</nav>
<div class="content-inner">

<header class="page-header">
  <div class="container-fluid">
    <h2 class="no-margin-bottom">Tables</h2>
  </div>
</header>

<div class="breadcrumb-holder container-fluid">
  <ul class="breadcrumb">
    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
    <li class="breadcrumb-item active">Tables</li>
  </ul>
</div>

<section class="tables">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-close">
            <div class="dropdown">
              <button type="button" id="closeCard3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-ellipsis-v"></i></button>
              <div aria-labelledby="closeCard3" class="dropdown-menu dropdown-menu-right has-shadow"><a href="#" class="dropdown-item remove"> <i class="fa fa-times"></i>Close</a><a href="#" class="dropdown-item edit"> <i class="fa fa-gear"></i>Edit</a></div>
            </div>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-striped table-hover">
                <thead>
                  <tr>
                    <th>Nama Produk</th>
                    <th>Harga</th>
                    <th>Status</th>
                    <th>Jumlah Barang</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach ($woos as $woo)
                  <tr>
                    <th>{{$woo['name']}}</th>
                    <th>{{$woo['regular_price']}}</th>
                    <th>{{$woo['status']}}</th>
                    <th>{{$woo['stock_quantity']}}</th>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <nav aria-label="...">
          <ul class="pagination">
            <li class="page-item">
              <a class="page-link" href="http://localhost/larawoo/public/product?posts_per_page={{ $params['per_page']}}&page={{ $previous }}" tabindex="-1">{{ $previous }}</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="http://localhost/larawoo/public/product?posts_per_page={{ $params['per_page']}}&page={{ $firstpage }}" tabindex="-1">{{ $firstpage }}</a>
            </li>
            <li class="page-item active">
              <a class="page-link" href="http://localhost/larawoo/public/product?posts_per_page={{ $params['per_page']}}&page={{ $current }}" <span class="sr-only">{{ $current }}</span></a>
            </li>
            <li class="page-item">
              <a class="page-link" href="http://localhost/larawoo/public/product?posts_per_page={{ $params['per_page']}}&page={{ $lastpage }}">{{ $lastpage }}</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="http://localhost/larawoo/public/product?posts_per_page=10&page={{ $next }}">{{ $next }}</a>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</section>
@endsection

this is my routes
Route::get('/product?posts_per_page=10&page={id}', 'ProductController@show');

When I execute the link there is an error 

"Undefined variable: params (View: C:\xampp\htdocs\larawoo\resources\views\product.blade.php)"

**Comment by pixelpeter** [comment]
I'm sorry, but this is **not** a problem related to this package.
Unfortunately I don't have the time to help you with an issue outside of the scope of this library
