### ISSUE TITLE
Connect to multiple woocommerce rest api's from one laravel installation

### ISSUE THREAD

**Issue by michaelchora** [pixelpeter/laravel5-woocommerce-api-client#39]
Is it possible to connect to multiple woocommerce rest api's with the one Laravel instance. I have a number of different websites that i would like to be able to get information from and send orders to from the one Laravel instance.

I had a bit of a look through the code, and im assuming i return a multidimensional array from the config/woocommerce.php file and then address that node of the array when doing the connection. But if there is already functionality in place, id rather not rewrite what already works.

**Comment by pixelpeter** [comment]
Nope.
See: https://github.com/pixelpeter/laravel5-woocommerce-api-client/issues/35#issuecomment-398747533
