### ISSUE TITLE
Using new api version v1

### ISSUE THREAD

**Issue by joberg86** [pixelpeter/laravel5-woocommerce-api-client#5]
Hi,

Thanks for the great wrapper, I was wondering if there is a way to use the new woocommerce api 
Maybe by including this options in the .env config?
api' => true,
'version' => 'wc/v1',

Regards

**Comment by pixelpeter** [comment]
I will give it a try and let you know the results

**Comment by joberg86** [comment]
Great, thank you!

**Comment by pixelpeter** [comment]
Please use version 2 for support of Woocommerce 2.6+
