### ISSUE TITLE
getShippingMethods and getPaymentMethods

### ISSUE THREAD

**Issue by tomas02061991** [pixelpeter/laravel5-woocommerce-api-client#7]
could it be implemented that all available shipping and payment methods could be retrieved?

**Comment by pixelpeter** [comment]
I will have a look at it.

**Comment by pixelpeter** [comment]
As you can see when you call the index of available actions/endpoints
```php
Woocommerce::get('')
```
there's nothing to retrieve the available payment methods.

For the shipping methods there are good news. You simply call
```php
Woocommerce::get('products/shipping_classes')
```
