### ISSUE TITLE
WoocommerceServiceProvider.php

### ISSUE THREAD

**Issue by imzeeshan** [pixelpeter/laravel5-woocommerce-api-client#9]
This code does not work
`
$this->mergeConfigFrom(
            __DIR__ . '/../config/woocommerce.php',
            'woocommerce'
        );`

Instead, it should be 

`$this->mergeConfigFrom(
            __DIR__ . '/../config/woocommerce.php',
            'Woocommerce'
        );
`

**Comment by pixelpeter** [comment]
I checked it again and it's working fine.
What tells you that it's not working?
